export default {
  products: [
    {
      _id: '1',
      name: 'Urban Thermal Zip Hoodie',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Urban Threads',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'StreetDef Tech Fleece',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'StreetDef',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'NightWalk Pullover',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'NightWalk',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Concrete Joggers',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Concrete',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Graphic Street Pants',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Urban Threads',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Utility Cargo Pants',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'StreetDef',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
